package com.shadowcheck.mobile.wifi.model

data class WifiNetwork(
    val ssid: String,
    val bssid: String,
    val capabilities: String,
    val frequency: Int,
    val signalLevel: Int,
    val timestamp: Long,
    val latitude: Double = 0.0,
    val longitude: Double = 0.0,
    val channel: Int = 0,
    val channelWidth: Int = 0,
    val centerFreq0: Int = 0,
    val centerFreq1: Int = 0,
    val standard: String = "",
    val maxDataRate: Int = 0,
    val is80211mc: Boolean = false,
    val isPasspoint: Boolean = false,
    val operatorFriendlyName: String = "",
    val venueName: String = "",
    val rcoi: String = "",
    val vendorOui: String = "",
    val vendorName: String = "",
    val altitude: Double = 0.0,
    val altitudeBarometric: Double = 0.0,
    val accuracy: Float = 0f,
    val speed: Float = 0f,
    val bearing: Float = 0f,
    val firstSeen: Long = timestamp,
    val lastSeen: Long = timestamp,
    val source: String = ""
)
